const LABEL_HIDDEN = "LABEL_HIDDEN";
const BUSINESS_PROCESS_NEW_BUSINESS = "New Business";
const BUSINESS_PROCESS_NAME_RESERVATION = "Name Reservation";
const MESSAGE_TYPE_TOAST = "TOAST_MESSAGE";
const MESSAGE_TYPE_SECTION_CHANGE = "SECTION_CHANGE";

export { LABEL_HIDDEN, BUSINESS_PROCESS_NEW_BUSINESS, BUSINESS_PROCESS_NAME_RESERVATION, MESSAGE_TYPE_TOAST, MESSAGE_TYPE_SECTION_CHANGE };