public class GlobalConstants {
    public static final String DOCUSIGNSTATUS = 'dsfs__docusign_status__c';
    public static final String FILEDETAILS = 'FileDetails__c';
    public static final String EXAMFILEERROR = 'Only the Exam Owner or Assistant Examiner can upload or delete Files';
    public static final String FILINGFILEERROR = 'Only the Reviewer can upload or delete Files';
    public static String SYSTEMADMIN = 'System Administrator';
    public static final String SESYSTEMADMIN = 'DCCA SEC/SEB System Administrator';
    public static final String CUSTOMCOMMUNITYLOGIN = 'DCCA BREG - CustomerCommunityLogin';

}