@isTest
private class sc_GlobalConstantsTest {
    @isTest
    static void testConstants() {
        System.assert(sc_GlobalConstants.READACCESS != null);
        System.assert(sc_GlobalConstants.APPLICATION_SUMMARY != null);
        System.assert(sc_GlobalConstants.REGISTRATIONDOCUMENTS != null);
        System.assert(sc_GlobalConstants.ERROR_APP_CACHE_NOT_FIND != null);
        System.assert(sc_GlobalConstants.SUBMITTED != null);
        System.assert(sc_GlobalConstants.USERSTR != null);
    }

}