public with sharing class TriggerHelper {
    public static Boolean disableAssociatedLicenseTrigger = false;
    public static Boolean disableAccountTrigger = false;
    public static Boolean disableApplicationTrigger = false;
    public static Boolean disableLicenseTrigger = false;
    public static Boolean disableLicenseClassificationTrigger = false;
    public static Boolean disableLicenseConditionsTrigger = false;
    public static Boolean disableEligibleCandidateLoadTrigger = false; //Added for case 00005582 
    public static Boolean disableExamResultLoadTrigger = false; //Added for case 00005651
}